# Generated by Django 6.0.2 on 2026-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_latitude_airport_longitude_flight_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='Manipal Airlines', max_length=100),
        ),
    ]
